# Generated by Django 5.1.3 on 2026-04-24 14:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_doctor_yearsofexperience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='booked', max_length=16)),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('doctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='authentication.doctor')),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='authentication.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('slotDuration', models.PositiveSmallIntegerField(default=30, editable=False)),
                ('doctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctorSchedules', to='authentication.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patientId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medicalRecord', to='authentication.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('sentAt', models.DateTimeField(auto_now_add=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientDiagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnosis', models.TextField()),
                ('dateDiagnosed', models.DateTimeField(auto_now_add=True)),
                ('appointmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientDiagnoses', to='clinic_management.appointment')),
                ('doctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientDiagnoses', to='authentication.doctor')),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientDiagnoses', to='authentication.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientPrescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prescription', models.TextField()),
                ('dose', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('isPermanent', models.BooleanField(default=False)),
                ('datePrescribed', models.DateTimeField(auto_now_add=True)),
                ('appointmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientPrescriptions', to='clinic_management.appointment')),
                ('doctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientPrescriptions', to='authentication.doctor')),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientPrescriptions', to='authentication.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('appointmentId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='clinic_management.appointment')),
                ('doctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='authentication.doctor')),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='authentication.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved')], default='available', max_length=16)),
                ('scheduleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeSlots', to='clinic_management.doctorschedule')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='timeSlotId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinic_management.timeslot'),
        ),
        migrations.AddIndex(
            model_name='doctorschedule',
            index=models.Index(fields=['doctorId', 'date'], name='clinic_mana_doctorI_f74735_idx'),
        ),
        migrations.AddConstraint(
            model_name='doctorschedule',
            constraint=models.UniqueConstraint(fields=('doctorId', 'date', 'startTime', 'endTime'), name='unique_doctor_schedule_window'),
        ),
        migrations.AddConstraint(
            model_name='doctorschedule',
            constraint=models.CheckConstraint(condition=models.Q(('startTime__lt', models.F('endTime'))), name='doctor_schedule_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='doctorschedule',
            constraint=models.CheckConstraint(condition=models.Q(('slotDuration', 30)), name='doctor_schedule_slot_duration_30'),
        ),
        migrations.AddIndex(
            model_name='patientdiagnosis',
            index=models.Index(fields=['patientId', 'dateDiagnosed'], name='clinic_mana_patient_9d4b17_idx'),
        ),
        migrations.AddConstraint(
            model_name='patientdiagnosis',
            constraint=models.UniqueConstraint(fields=('appointmentId', 'doctorId'), name='unique_diagnosis_per_appointment_doctor'),
        ),
        migrations.AddIndex(
            model_name='patientprescription',
            index=models.Index(fields=['patientId', 'datePrescribed'], name='clinic_mana_patient_dbb514_idx'),
        ),
        migrations.AddConstraint(
            model_name='patientprescription',
            constraint=models.UniqueConstraint(fields=('appointmentId', 'doctorId'), name='unique_prescription_per_appointment_doctor'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['doctorId', 'createdAt'], name='clinic_mana_doctorI_18f9c4_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['patientId', 'createdAt'], name='clinic_mana_patient_c98f5b_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['scheduleId', 'status'], name='clinic_mana_schedul_9c3e54_idx'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('scheduleId', 'startTime', 'endTime'), name='unique_schedule_timeslot_window'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.CheckConstraint(condition=models.Q(('startTime__lt', models.F('endTime'))), name='timeslot_start_before_end'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctorId', 'status'], name='clinic_mana_doctorI_6d67f1_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patientId', 'status'], name='clinic_mana_patient_1abfd7_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['createdAt'], name='clinic_mana_created_f28136_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'booked')), fields=('timeSlotId',), name='unique_booked_appointment_per_slot'),
        ),
    ]
