# Generated by OpenCode on 2026-04-24

import uuid

from django.db import migrations


def create_missing_medical_records(apps, schema_editor):
    Patient = apps.get_model("authentication", "Patient")
    MedicalRecord = apps.get_model("clinic_management", "MedicalRecord")

    existing_patient_ids = set(
        MedicalRecord.objects.values_list("patientId_id", flat=True)
    )
    records_to_create = []
    for patient in Patient.objects.all().iterator():
        if patient.pk not in existing_patient_ids:
            records_to_create.append(
                MedicalRecord(
                    id=uuid.uuid4(),
                    patientId_id=patient.pk,
                )
            )

    if records_to_create:
        MedicalRecord.objects.bulk_create(records_to_create)


class Migration(migrations.Migration):
    dependencies = [
        ("clinic_management", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_missing_medical_records,
            migrations.RunPython.noop,
        ),
    ]
